set(
  OML_SOURCE_FILE_MANIFEST
    src/Latch.cpp
    src/Logger.cpp
    src/main.cpp
    src/scheduler/Worker.cpp
    src/scheduler/WorkerPool.cpp
    ${PLATFORM_DIR}/CPUIdentifier.cpp
    ${PLATFORM_DIR}/PrimitiveIO.cpp
    $<$<CXX_COMPILER_ID:MSVC>:${PLATFORM_DIR}/winmain.cpp>
)

if(MSVC)
  list(
    APPEND
    OML_SOURCE_FILE_MANIFEST
      ${PLATFORM_DIR}/winmain.cpp
  )
endif()
