name: CI

on:
  push:
    branches:
      - main

jobs:
  msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1 # defaults to x64
      - uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.243.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - name: Init submodules
        run: git submodule update --init --recursive --depth 1
      - name: build.rb
        run: ruby.exe build.rb -t msvc -b ${{ matrix.build_type }} -v build test
